# Generated by Django 4.2.4 on 2023-09-06 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_tokens'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tokens',
        ),
    ]
