# Generated by Django 4.2.1 on 2023-05-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_customer_delete_comments_delete_friends_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
