# Generated by Django 4.2.1 on 2023-05-17 00:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_users_avatar_users_created_at_users_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="participation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(max_length=20)),
                ("task_id", models.IntegerField(max_length=20)),
                (
                    "is_accepted",
                    models.BooleanField(default=False, verbose_name="是否接受邀请"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="参与任务时间"
                    ),
                ),
            ],
        ),
    ]
